admin/controllers/LocationController.php
<?php

namespace admin\controllers;

use admin\models\LocationSearch;
use admin\models\User;
use common\models\Countries;
use common\models\Regions;
use Throwable;
use Yii;
use common\models\Locations;
use yii\data\ActiveDataProvider;
use yii\db\Expression;
use yii\db\Transaction;
use yii\helpers\ArrayHelper;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;

/**
 * LocationController implements the CRUD actions for Locations model.
 */
class LocationController extends BaseController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ]);
    }

    /**
     * Lists all Locations models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new LocationSearch();

        if ($this->user->role === User::ROLE_MANAGER) {
            $searchModel->id = $this->user->location_id;
        }

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Locations model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionBalance()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Locations::find(),
        ]);

        return $this->render('balance', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Locations model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $locationModel = new Locations();
        $countryModel = new Countries();
        $regionModel = new Regions();

        if (Yii::$app->request->isPost === true) {
            $transaction = Yii::$app->db->beginTransaction(Transaction::SERIALIZABLE);

            try {
                $isLoaded = $locationModel->load(Yii::$app->request->post());
                $isValid = $locationModel->validate(['name', 'share']);

                if ($isLoaded === false || $isValid === false) {
                    $transaction->rollBack();

                    return $this->render('create', [
                        'locationModel' => $locationModel,
                        'countryModel' => $countryModel,
                        'regionModel' => $regionModel,
                    ]);
                }

                if ((int) $locationModel->region_id === 0) {
                    $isRegionLoaded = $regionModel->load(Yii::$app->request->post());

                    if ((int) $regionModel->country_id === 0) {
                        $isCountryLoaded = $countryModel->load(Yii::$app->request->post());
                        $isCountryValid = $countryModel->validate();

                        if ($isCountryLoaded !== false || $isCountryValid !== false) {
                            $countryModel->save(false);
                            $regionModel->country_id = $countryModel->id;
                        } else {
                            $transaction->rollBack();

                            return $this->render('create', [
                                'locationModel' => $locationModel,
                                'countryModel' => $countryModel,
                                'regionModel' => $regionModel,
                            ]);
                        }
                    }

                    $isRegionValid = $regionModel->validate();

                    if ($isRegionLoaded !== false || $isRegionValid !== false) {
                        $regionModel->save(false);
                        $locationModel->region_id = $regionModel->id;
                    } else {
                        $transaction->rollBack();

                        return $this->render('create', [
                            'locationModel' => $locationModel,
                            'countryModel' => $countryModel,
                            'regionModel' => $regionModel,
                        ]);
                    }
                }

                $isSaved = $locationModel->save();

                if ($isSaved === false) {
                    $transaction->rollBack();

                    return $this->render('create', [
                        'locationModel' => $locationModel,
                        'countryModel' => $countryModel,
                        'regionModel' => $regionModel,
                    ]);
                }

                if ($locationModel->save()) {
                    $transaction->commit();

                    return $this->redirect(['view', 'id' => $locationModel->id]);
                }
            } catch (Throwable $e) {
                Yii::error($e);

                $transaction->rollBack();
            }
        }

        return $this->render('create', [
            'locationModel' => $locationModel,
            'countryModel' => $countryModel,
            'regionModel' => $regionModel,
        ]);
    }

    /**
     * Updates an existing Locations model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $locationModel = $this->findModel($id);
        $regionModel = $locationModel->region ?? new Regions();
        $countryModel = $locationModel->country ?? new Countries();

        if (Yii::$app->request->isPost === true) {
            $transaction = Yii::$app->db->beginTransaction(Transaction::SERIALIZABLE);

            try {
                $isLoaded = $locationModel->load(Yii::$app->request->post());
                $isValid = $locationModel->validate(['name', 'share']);

                if ($isLoaded === false || $isValid === false) {
                    $transaction->rollBack();

                    return $this->render('update', [
                        'locationModel' => $locationModel,
                        'countryModel' => $countryModel,
                        'regionModel' => $regionModel,
                    ]);
                }

                if ((int) $locationModel->region_id === 0) {
                    $isRegionLoaded = $regionModel->load(Yii::$app->request->post());

                    if ((int) $regionModel->country_id === 0) {
                        $isCountryLoaded = $countryModel->load(Yii::$app->request->post());
                        $isCountryValid = $countryModel->validate();

                        if ($isCountryLoaded !== false || $isCountryValid !== false) {
                            $countryModel->save(false);
                            $regionModel->country_id = $countryModel->id;
                        } else {
                            $transaction->rollBack();

                            return $this->render('update', [
                                'locationModel' => $locationModel,
                                'countryModel' => $countryModel,
                                'regionModel' => $regionModel,
                            ]);
                        }
                    }

                    $isRegionValid = $regionModel->validate();

                    if ($isRegionLoaded !== false || $isRegionValid !== false) {
                        $regionModel->save(false);
                        $locationModel->region_id = $regionModel->id;
                    } else {
                        $transaction->rollBack();

                        return $this->render('update', [
                            'locationModel' => $locationModel,
                            'countryModel' => $countryModel,
                            'regionModel' => $regionModel,
                        ]);
                    }
                }

                $isSaved = $locationModel->save();

                if ($isSaved === false) {
                    $transaction->rollBack();

                    return $this->render('update', [
                        'locationModel' => $locationModel,
                        'countryModel' => $countryModel,
                        'regionModel' => $regionModel,
                    ]);
                }

                if ($locationModel->save()) {
                    $transaction->commit();

                    return $this->redirect(['view', 'id' => $locationModel->id]);
                }
            } catch (Throwable $e) {
                Yii::error($e);

                $transaction->rollBack();
            }
        }


        return $this->render('update', [
            'locationModel' => $locationModel,
            'countryModel' => $countryModel,
            'regionModel' => $regionModel,
        ]);
    }

    /**
     * Deletes an existing Locations model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Locations model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Locations the loaded model

admin/views/location/_form.php
<?php

use admin\widgets\DropDownList;
use common\models\Countries;
use common\models\Regions;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $locationModel common\models\Locations */
/* @var $countryModel common\models\Countries */
/* @var $regionModel common\models\Regions */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="locations-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($locationModel, 'region_id')->widget(DropDownList::class, [
        'data' => ArrayHelper::merge([ '0' => 'Добавить регион'], ArrayHelper::map(Regions::find()->all(), 'id', 'name')),
    ]) ?>

    <div class="country-form">
        <?= $form->field($regionModel, 'country_id')->widget(DropDownList::class, [
            'data' => ArrayHelper::merge([ '0' => 'Добавить страну'], ArrayHelper::map(Countries::find()->all(), 'id', 'name')),
        ]) ?>
    </div>

    <div class="new-country-form">
        <?= $form->field($countryModel, 'name', ['enableClientValidation' => false])->textInput()->label('Название страны'); ?>
    </div>

    <div class="region-form">
        <?= $form->field($regionModel, 'name', ['enableClientValidation' => false])->textInput()->label('Название региона'); ?>
    </div>
    <?= $form->field($locationModel, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($locationModel, 'share')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

admin/views/location/balance.php
<?php

use admin\assets\LocationsBalanceAsset;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Баланс филиалов';
$this->params['breadcrumbs'][] = $this->title;

LocationsBalanceAsset::register($this);
?>
<div class="locations-index" id="location-balance">

    <h1><?= Html::encode($this->title) ?></h1>
    <div class="modal fade" id="locations-balance-modal" tabindex="-1" role="dialog" aria-labelledby="locations-balance-modal-label">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="locations-balance-modal-label">Коррекция баланса</h4>
                    <p class=divider></p>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="location-name" class="control-label">Аккаунт:</label>
                                    <select type="text" v-model="currentLocation" class="form-control" id="location-name">
                                        <template v-for="location in locations">
                                            <option v-bind:value="location">{{location.name}}</option>
                                        </template>
                                    </select>
                                <p class="help-block">Баланс: {{ currentLocation.balance }} ₽</p>
                            </div>
                            <div class="form-group">
                                <label for="account-value" class="control-label">Новый баланс:</label>
                                <input v-model="newLocationBalance"  type="text" class="form-control" id="account-value">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Отменить</button>
                    <button type="button" class="btn btn-primary" @click="updateLocationBalance">Сохранить</button>
                </div>
            </div>
        </div>
    </div>
    <p>
        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#locations-balance-modal">
            Коррекция
        </button>
    </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            [
                'attribute' => 'name',
                'contentOptions' => [
                    'style' => 'width: 10%',
                ],
            ],
            [
                'attribute' => 'balance',
                'format' => 'currency',
                'contentOptions' => [
                    'style' => 'width: 10%',
                ],
            ],
        ],
    ]); ?>


</div>

admin/views/location/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $locationModel common\models\Locations */
/* @var $countryModel common\models\Countries */
/* @var $regionModel common\models\Regions */

$this->title = 'Добавить Филиал';
$this->params['breadcrumbs'][] = ['label' => 'Филиалы', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="locations-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'locationModel' => $locationModel,
        'countryModel' => $countryModel,
        'regionModel' => $regionModel,
    ]) ?>

</div>

admin/views/location/index.php
<?php

use admin\models\User;
use admin\widgets\DropDownList;
use common\models\Countries;
use common\models\Locations;
use common\models\Regions;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Филиалы';
$this->params['breadcrumbs'][] = $this->title;
$role = Yii::$app->user->getIdentity()->role;

?>
<div class="locations-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?php if ($role === User::ROLE_ADMIN) {
             echo Html::a('Добавить офис', ['create'], ['class' => 'btn btn-success']);
        } ?>
        <?= Html::a('Сбросить фильтр', ['index'], ['class' => 'btn btn-success']) ?>

    </p>


    <?= GridView::widget([
        'options' => [
            'class' => 'table-responsive',
        ],
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            'id',
            [
                'attribute' => 'country_id',
                'label' => 'Страна',
                'filter' => DropDownList::widget([
                    'model' => $searchModel,
                    'attribute' => 'country_id',
                    'data' => ArrayHelper::map(Countries::find()->all(), 'id', 'name'),
                ]),
                'value' => function ($model) {
                    /* @var $model Locations */
                    return $model->country->name ?? null;
                },
                'headerOptions' => [
                    'style' => 'width: 10%',
                ],
            ],
            [
                'attribute' => 'region_id',
                'filter' => DropDownList::widget([
                    'model' => $searchModel,
                    'attribute' => 'region_id',
                    'data' => ArrayHelper::map(Regions::find()->all(), 'id', 'name'),
                ]),
                'headerOptions' => [
                    'style' => 'width: 10%',
                ],
                'value' => function ($model) {
                    /* @var $model Locations */
                    return $model->region->name ?? null;
                },
            ],
            'name',

            [
                'attribute' => 'share',
                'headerOptions' => [
                    'style' => 'width: 20%',
                ],
                'value' => function ($model) {
                    /* @var $model Locations */
                    if ($model->share !== null) {
                        return sprintf('%d%%', $model->share);
                    }

                    return null;
                },
            ],
            'balance:currency',
            'created_at',
            //'updated_at',
            //'deleted_at',

            [
                'class' => 'admin\components\grid\ActionWithAccessColumn',
                'role' => $role,
            ],
        ],
    ]); ?>


</div>

admin/views/location/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $locationModel common\models\Locations */
/* @var $countryModel common\models\Countries */
/* @var $regionModel common\models\Regions */

$this->title = 'Редактировать: ' . $locationModel->name;
$this->params['breadcrumbs'][] = ['label' => 'Филиалы', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $locationModel->name, 'url' => ['view', 'id' => $locationModel->id]];
$this->params['breadcrumbs'][] = 'Редактировать';
?>
<div class="locations-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'locationModel' => $locationModel,
        'countryModel' => $countryModel,
        'regionModel' => $regionModel,
    ]) ?>

</div>

admin/views/location/view.php
<?php

use admin\models\User;
use common\models\Locations;
use yii\helpers\Html;
use yii\web\YiiAsset;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Locations */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Филиалы', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
$role = Yii::$app->user->getIdentity()->role;

YiiAsset::register($this);

?>
<div class="locations-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?php if ($role === User::ROLE_ADMIN) {
            echo Html::a('Изменить', ['location/update', 'id' => $model->id], ['class' => 'btn btn-primary']);
            echo Html::a('Удалить', ['location/delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => 'Are you sure you want to delete this item?',
                    'method' => 'post',
                ],
            ]);
        } ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            [
                'attribute' => 'country_id',
                'label' => 'Страна',
                'value' => function ($model) {
                    /* @var $model Locations */
                    return $model->country->name ?? null;
                },
            ],
            [
                'attribute' => 'region_id',
                'value' => function ($model) {
                    /* @var $model Locations */
                    return $model->region->name ?? null;
                },
            ],
            'name',
            'share',
            'created_at',
            'updated_at',
            'deleted_at',
        ],
    ]) ?>

</div>